### PR TITLE
CEO: Add Discards where necessary

### LINKED ISSUE #5546: CEO Lowell does not work if the CEO deck is empty/reshuffled during that action
Please include:
1. Lowell fizzles and does not count as an action.
2. Start a new game with 4 CEOs and 5 Players. Use Lowell (used gen 7, but not sure if gen matters).
3. image

URL: https://terraforming-mars.herokuapp.com/spectator?id=secd792a86185
Player color: yellow
Step: 383
Version: 648b01c, built at Sat, 01 Apr 2023 02:28:32 GMT
Browser: Chrome 111

### LINKED ISSUE #5607: CEOs are not being discarded
Related to #5546, but might become more of an issue with Prelude/Corps drawing CEOs.  They're not being discarded, but instead are just being cast into void after selection.

Expected behaviour is that they'd be put into the ceoDiscard pile, and reshuffled into draw if needed

### PR DESCRIPTION
**Pull request by d-little**
This should cover all our bases

Fixes #5607
Fixes #5546

Also standardised some of the wording/language on these items

### CODE REVIEW

File: src/server/cards/ceos/Lowell.ts [hunk 1]
```diff
@@ -35,27 +35,33 @@ export class Lowell extends CeoCard {
...
     ];
 
-    cardsDrawn.forEach((card) => {
-      if (card.canPlay?.(player) === false) {
-        cardsDrawn.splice(cardsDrawn.indexOf(card), 1);
-        game.log('${0} was discarded as ${1} could not play it,', (b) => b.card(card).player(player), {reservedFor: player});
+    ceosDrawn.forEach((ceo) => {
+      if (ceo.canPlay?.(player) === false) {
+        game.ceoDeck.discard(ceo);
+        ceosDrawn.splice(ceosDrawn.indexOf(ceo), 1);
```
Comment (kberg) [inline src/server/cards/ceos/Lowell.ts:47]: Another good use of `inplaceRemove`

File: src/server/cards/ceos/Lowell.ts [hunk 2]
```diff
@@ -35,27 +35,33 @@ export class Lowell extends CeoCard {
...
+      ceosDrawn.filter((c) => c !== chosenCeo).forEach((c) => game.ceoDeck.discard(c));
+      // Remove Lowell from played cards
+      const lowellIndex = player.playedCards.findIndex((c) => c.name === this.name);
+      player.playedCards.splice(lowellIndex, 1);
+      // Add Lowell to Discard pile
       game.ceoDeck.discard(this);
-
-      return player.playCard(card);
+      // Play the new CEO
+      player.playCard(chosenCeo);
```
Comment (kberg) [inline src/server/cards/ceos/Lowell.ts:63]: CEOs playCard returns void?

**Review by kberg — APPROVED** [review]
Minor stuff. Good PR

File: src/server/cards/ceos/Lowell.ts (hunk 2 above)
Comment (d-little) [reply src/server/cards/ceos/Lowell.ts:63]: `undefined`, its the same mechanism as project cards

File: src/server/cards/ceos/Lowell.ts (hunk 1 above)
Comment (d-little) [reply src/server/cards/ceos/Lowell.ts:47]: This raises a question for me, does modifying a list which is being iterated over cause problems in JS?

Im guessing not.  Python _hates_ it, never ever modify a container you're iterating on!

File: src/server/cards/ceos/Lowell.ts (hunk 2 above)
Comment (kberg) [reply src/server/cards/ceos/Lowell.ts:63]: Then I recommend returning it. That way if it returns something that's not undefined, it can get processed.

File: src/server/cards/ceos/Lowell.ts (hunk 1 above)
Comment (kberg) [reply src/server/cards/ceos/Lowell.ts:47]: Oh right, uh... good question, don't know. Perhaps forEach helps out. Perhaps it's wrong in this case.

Comment (d-little) [reply src/server/cards/ceos/Lowell.ts]: I got rid of the loop entirely, it felt.. better

(For future readers: Yes, iterating over a container and removing items will cause it to skip indexes and migraines)

**Comment by d-little** [comment]
> Minor stuff. Good PR

Ready for rereview!
