### PR TITLE
Make Asteroid Standard Project compatible with Aurorai

### LINKED ISSUE #4308: [pf] New Aurorai payment regression
Bug report for Aurorai: After paying the first starting data resources from Aurorai, you were not able to play and pay the standard project again which you have selected first (in our case the standard asteroid) if you have less money (than the cost of the standard project) but enough data to pay the difference.

### PR DESCRIPTION
**Pull request by kberg**
Fixes #4308

### CODE REVIEW

File: src/cards/base/standardProjects/AsteroidStandardProject.ts [hunk 1]
```diff
@@ -24,9 +25,7 @@ export class AsteroidStandardProject extends StandardProjectCard {
     if (player.game.getTemperature() === constants.MAX_TEMPERATURE) {
       return false;
     }
-    return player.canAfford(this.cost, {
-      tr: {temperature: 1},
-    });
+    return super.canAct(player);
```
Comment (kberg) [inline src/cards/base/standardProjects/AsteroidStandardProject.ts:28]: Basically this was due to AsteroidStandardProject not using the same pattern the other standard projects use.

**Review by nwai90 — APPROVED** [review]
