### PR TITLE
Mons Insurance should remove MC when played in as solo.

### LINKED ISSUE #3342: rules error: Mons Insurance should lose 3 MC for any "actual" attack on the neutral opponent
(I also checked if the same happens when I have 3+ MC, and it does.)

In the solo game, even though attacks against the neutral "player" are invisible, they are always treated as having actually happened, and thus Mons is forced to pay.

In case of a resource attack, the Mons player will want to choose whether to attack or not; it may sometimes be worth the 3 MC (such as with a steal attack), sometimes not.

### PR DESCRIPTION
**Pull request by kberg**
Fixes #3342

### CODE REVIEW

File: src/deferredActions/DecreaseAnyProduction.ts [hunk 1]
```diff
@@ -22,7 +23,12 @@ export class DecreaseAnyProduction implements DeferredAction {
   ) { }
 
   public execute() {
-    if (this.player.game.isSoloMode()) return undefined;
+    if (this.player.game.isSoloMode()) {
+      if (this.player.game.monsInsuranceOwner === this.player.id) {
```
Comment (kberg) [inline src/deferredActions/DecreaseAnyProduction.ts:27]: I don't like this repetition. Any thoughts?

File: src/cards/promo/MonsInsurance.ts [hunk 2]
```diff
@@ -42,4 +42,27 @@ export class MonsInsurance extends Card implements ICorporationCard {
     player.game.monsInsuranceOwner = player.id;
     return undefined;
   }
+
+  // When `insured` is undefined, it's the neutral player.
+  public payDebt(player: Player, insured : Player | undefined) {
+    if (player !== insured) {
+      const retribution = Math.min(player.megaCredits, 3);
+      if (insured) insured.megaCredits += retribution;
+      player.deductResource(Resources.MEGACREDITS, retribution);
```
Comment (kberg) [inline src/cards/promo/MonsInsurance.ts:51]: This is a small change -- it used to be `3` instead of `retribution` which is sometimes too large.  Reported illegal state.

File: src/cards/promo/MonsInsurance.ts [hunk 3]
```diff
@@ -42,4 +42,27 @@ export class MonsInsurance extends Card implements ICorporationCard {
     player.game.monsInsuranceOwner = player.id;
     return undefined;
   }
+
+  // When `insured` is undefined, it's the neutral player.
+  public payDebt(player: Player, insured : Player | undefined) {
```
Comment (kberg) [inline src/cards/promo/MonsInsurance.ts:47]: Hmm. `payDebt` - got a better name?

File: src/deferredActions/DecreaseAnyProduction.ts (hunk 1 above)
Comment (bafolts) [reply src/deferredActions/DecreaseAnyProduction.ts:27]: To avoid this duplication the only thought I have is introducing a static function on `MonsInsurance. Say there were a function named `payDebt` on `MonsInsurance`. One could then call it with.

```
MonsInsurance.payDept(player, insured)
```

I don't think we need any information on the instance of the card but we could find it if need be.

Comment (bafolts) [reply src/deferredActions/DecreaseAnyProduction.ts]: @kberg I am curious what you think of this suggestion? What you have seems fine but I think this static could avoid the duplicated code.

Comment (kberg) [reply src/deferredActions/DecreaseAnyProduction.ts]: Hi! I basically did that, I think. `MonsInsurance` is still possibly a little cluttered. Where's the duplicated code now?

**Review by bafolts — APPROVED** [review]

File: src/deferredActions/DecreaseAnyProduction.ts (hunk 1 above)
Comment (bafolts) [reply src/deferredActions/DecreaseAnyProduction.ts]: I didn't see you had made the change.
