### PR TITLE
clear customCorporationsList if not selected

### LINKED ISSUE #4046: Creating a new game with 4 players does not allow 3 corps each
I run a TM server on a raspberry pi, version info `deployed: Thu, 13 Jan 2022 18:42:43 -0500 version: 911d573ee`

Creating a new game with 4 players does not allow 3 corps each.

**Repro steps**
1. Navigate to `/new-game` URL.
2. Load settings file (see [tm_settings.txt](https://github.com/terraforming-mars/terraforming-mars/files/8010558/tm_settings.txt)).  This file includes 5 players and some customised settings.
3. Make the following changes:
  i. Change number of players to 4.
  ii. Unselected `Prelude`.
  iii. Unselected `Custom Corporation list`.
  iv. Selected `Random official` board.
  v. Increase starting corporations to 3.
  vi. Click `Create game`

**Expected result**
A new game is created

**Actual result**
Get the error "Must select at least 12 corporations".

I clicked on `Custom Corporation list` just to check and see that there are 12 corporations selected, see attached screenshot.  The workaround is to just start with a clean slate and not an existing preset.

image

### PR DESCRIPTION
**Pull request by bafolts**
This clears the custom corporations list if the showCorporationList is toggled off. After fixed an issue I saw in console logs where `game` was `undefined` while I was testing this change.

This can close #4046

### CODE REVIEW

File: src/client/components/GameHome.vue [hunk 1]
```diff
@@ -10,7 +10,7 @@
             <Button title="copy" size="tiny" @click="copyUrl(player.id)"/>
             <span v-if="isPlayerUrlCopied(player.id)" class="copied-notice">Playable link for {{player.name}} copied to clipboard <span class="dismissed" @click="setCopiedIdToDefault" >dismiss</span></span>
           </li>
-          <li v-if="game.spectatorId">
+          <li v-if="game !== undefined && game.spectatorId">
```
Comment (kberg) [inline src/client/components/GameHome.vue:13]: `game?.spectatorId` will do the same job

**Review by kberg — APPROVED** [review]

File: src/client/components/GameHome.vue (hunk 1 above)
Comment (bafolts) [reply src/client/components/GameHome.vue:13]: I am an old dog and this is a new trick.
